# Generated by Django 2.0 on 2018-12-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181207_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetail',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Genre'),
        ),
        migrations.AddField(
            model_name='artistdetail',
            name='sex_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Sex'),
        ),
    ]
