# Generated by Django 2.0 on 2018-12-07 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181207_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('caption', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Color')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Genre')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Size')),
                ('subgenre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SubGenre')),
            ],
        ),
    ]
