# Generated by Django 2.0 on 2018-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181207_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdetail',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buyerdetail',
            name='credit_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buyerdetail',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='buyerdetail',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
