# Generated by Django 2.0 on 2018-12-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181207_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Genre'),
        ),
    ]
