# Generated by Django 2.0 on 2018-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181207_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdetail',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
