# Generated by Django 2.0.8 on 2019-02-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181207_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, default=0)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ready_as_buyer', models.BooleanField(default=False)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('ready_as_artist', models.BooleanField(default=False)),
                ('debuted', models.BooleanField(default=False)),
                ('approved', models.IntegerField(blank=True, default=0)),
                ('ticket', models.IntegerField(blank=True, default=0)),
                ('artist_name', models.CharField(blank=True, default='', max_length=30)),
                ('profile', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('place', models.CharField(blank=True, default='', max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=20)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=20)),
                ('bank_branch_code', models.CharField(blank=True, default='', max_length=20)),
                ('bank_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=20)),
                ('sex', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='api.Sex')),
            ],
        ),
        migrations.RemoveField(
            model_name='artistdetail',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artistdetail',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='artistdetail',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='buyerdetail',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.DeleteModel(
            name='ArtistDetail',
        ),
        migrations.DeleteModel(
            name='BuyerDetail',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
