# Generated by Django 2.0.8 on 2019-02-22 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190218_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Work')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='icon',
            field=models.FileField(blank=True, default='icons/default.jpg', upload_to='icons/'),
        ),
    ]
