# Generated by Django 2.0.8 on 2019-02-25 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190222_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, upload_to='workImages/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='icon',
            field=models.ImageField(blank=True, default='icons/default.jpg', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
