# Generated by Django 2.0.8 on 2019-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190225_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='workImages/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='workImages/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='workImages/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='workImages/'),
        ),
    ]
