# Generated by Django 2.0.8 on 2019-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190225_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='workImages/'),
        ),
    ]
