# Generated by Django 2.0.8 on 2019-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190225_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image1',
            field=models.ImageField(blank=True, default=None, upload_to='workImages/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='workImages/'),
        ),
    ]
