# Generated by Django 2.0.8 on 2019-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190225_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image1',
            field=models.ImageField(blank=True, upload_to='workImages/'),
        ),
    ]
